BEGIN;

CREATE TABLE users(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    createdAt TIMESTAMPTZ NOT NULL DEFAULT now(),
    updatedAt TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE OR REPLACE FUNCTION set_updatedAt() RETURNS trigger AS $$
BEGIN
  NEW.updatedAt := now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW EXECUTE FUNCTION set_updatedAt();

-- тут была функция для обновления updatedAt при изменении любых строк в юзере

CREATE TABLE thoughts(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    createdAt TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX ix_thoughts_user_id ON thoughts(user_id);
CREATE INDEX ix_thoughts_createdAt ON thoughts(createdAt);
-- индексы, чтобы быстрее находить значения

CREATE TABLE stages(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    thought_id BIGINT NOT NULL REFERENCES thoughts(id) ON DELETE CASCADE,
    stage SMALLINT NOT NULL CHECK (stage BETWEEN 1 AND 4),
    capture TEXT NOT NULL,
    createdAt TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX ix_stage_thought_id ON stages(thought_id);
CREATE INDEX ix_stage_createdAt ON stages(createdAt);

CREATE TABLE moods(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    mood TEXT NOT NULL,
    createdAt TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX ix_mood_user_id ON moods(user_id);
CREATE INDEX ix_mood_createdAt ON moods(createdAt);

COMMIT;

-- чтобы запустить и создать необходимые таблице, в консоли пропиши (предварительно обязательно установить postgres и добавить путь в PATH):
-- createdb -U postgres -h localhost -p 5432 aura
-- теперь создать таблички по схеме:
-- psql -h localhost -p 5432 -U postgres -d aura -f models\schema.sql
-- В С Ё ! теперь бдшка отображается в pdAdmin, пляшем
